# -----------------------------------------------------
# User Overrides for Omarchy Hyprland
# -----------------------------------------------------

# --- Monitors ---
env = GDK_SCALE,1.75
monitor=,preferred,auto,1.67

# --- Input ---
input {
  kb_layout = us, ua
  kb_options = compose:caps 
  repeat_rate = 40
  repeat_delay = 600
  numlock_by_default = true
  
  touchpad {
     natural_scroll = true
     scroll_factor = 0.4
  }
}

# windowrule = scrolltouchpad 1.5, class:(Alacritty|kitty)
# windowrule = scrolltouchpad 0.2, class:com.mitchellh.ghostty

# --- Keybindings ---
$terminal = uwsm-app -- xdg-terminal-exec
$browser = omarchy-launch-browser

bindd = SUPER, RETURN, Terminal, exec, $terminal --working-directory="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, $browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, T, Activity, exec, omarchy-launch-tui btop
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-or-focus signal "uwsm-app -- signal-desktop"
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus "^obsidian$" "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password

# Web Apps
bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT ALT, A, Grok, exec, omarchy-launch-webapp "https://grok.com"
bindd = SUPER SHIFT, C, Calendar, exec, omarchy-launch-webapp "https://app.hey.com/calendar/weeks/"
bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-webapp "https://app.hey.com"
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"
bindd = SUPER SHIFT ALT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER SHIFT CTRL, G, Google Messages, exec, omarchy-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
bindd = SUPER SHIFT, P, Google Photos, exec, omarchy-launch-or-focus-webapp "Google Photos" "https://photos.google.com/"
bindd = SUPER SHIFT, X, X, exec, omarchy-launch-webapp "https://x.com/"
bindd = SUPER SHIFT ALT, X, X Post, exec, omarchy-launch-webapp "https://x.com/compose/post"

# System
bind = ALT, SPACE, exec, hyprctl switchxkblayout all next

# Handy - toggle recording with SIGUSR2 signal
bindd = SUPER, H, Handy toggle recording, exec, pkill -USR2 -n handy

# Resize windows
bind = SUPER CTRL, right, resizeactive, 30 0
bind = SUPER CTRL, left,  resizeactive, -30 0
bind = SUPER CTRL, up,    resizeactive, 0 -30
bind = SUPER CTRL, down,  resizeactive, 0 30

# --- Auto Start ---
exec-once = kanshi
exec = kanshictl reload

# --- Animations ---
animations {
    enabled = false
}
